name: cancer-dl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  - pytorch
  - torchvision
  - torchaudio
  - jupyterlab
  - ipykernel
  - plotly
  - kaggle
  - notebook
  - pip
  - pip:
      - albumentations
      - opencv-python
      - tensorflow-addons

